version: '3.8'

services:
  central_db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: central_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - central_data:/data/pgdata
      - ./distributed_db/general/:/general
      - ./distributed_db/central/settings:/settings
    networks:
      - club_net

  club1_db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: club1_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - club1_data:/data/pgdata
      - ./distributed_db/general/:/general
      - ./distributed_db/club_1/settings:/settings
    networks:
      - club_net

  club2_db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: club2_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - club2_data:/data/pgdata
      - ./distributed_db/general/:/general
      - ./distributed_db/club_2/settings:/settings
    networks:
      - club_net

  club3_db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: club3_db
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - club3_data:/data/pgdata
      - ./distributed_db/general/:/general
      - ./distributed_db/club_3/settings:/settings
    networks:
      - club_net

volumes:
  central_data:
  club1_data:
  club2_data:
  club3_data:

networks:
  club_net:
    driver: bridge
